# -Wall turns on all warnings
# -g2012 selects the 2012 version of iVerilog
IVERILOG=iverilog -Wall -Wno-sensitivity-entire-vector -Wno-sensitivity-entire-array -g2012 -y ./ -I ./
VVP=vvp
VIVADO=vivado -mode batch -source

# Add any new source files needed for the final bitstream here
SRCS=pulse_generator.sv pwm.sv triangle_generator.sv debouncer.sv edge_detector.sv edge_detector_moore.sv

# Look up .PHONY rules for Makefiles
.PHONY: clean submission remove_solutions

test_pulse_generator: tests/test_pulse_generator.sv pulse_generator.sv
	${IVERILOG} $^ -o test_pulse_generator.bin && ${VVP} test_pulse_generator.bin

test_pwm: tests/test_pwm.sv pulse_generator.sv pwm.sv
	@echo "This might take a while, we're testing a lot of clock cycles!"
	${IVERILOG} $^ -o test_pwm.bin && ${VVP} test_pwm.bin

test_triangle_generator: tests/test_triangle_generator.sv triangle_generator.sv
	${IVERILOG} $^ -o test_triangle_generator.bin && ${VVP} test_triangle_generator.bin

test_debouncer : tests/test_debouncer.sv debouncer.sv
	${IVERILOG} $^ -o test_debouncer.bin && ${VVP} test_debouncer.bin

test_main: tests/test_main.sv main.sv $(SRCS)
	@echo "This might take a while, we're testing a lot of clock cycles!"
	@echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	@echo "!!!! This test can generate 100s of MB easily            !!!!"
	@echo "!!!! be careful if you are low on disk space!            !!!!"
	@echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	${IVERILOG} $^ -o test_main.bin && ${VVP} test_main.bin

test_light_sequencer: tests/test_light_sequencer.sv light_sequencer.sv $(SRCS)
	@echo "This might take a while, we're testing a lot of clock cycles!"
	@echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	@echo "!!!! This test can generate 100s of MB easily            !!!!"
	@echo "!!!! be careful if you are low on disk space!            !!!!"
	@echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	${IVERILOG} $^ -o test_light_sequencer.bin && ${VVP} test_light_sequencer.bin

test_edge_detectors : test_edge_detectors.sv edge_detector.sv edge_detector_moore.sv
	${IVERILOG} $^ -o test_edge_detectors.bin && ${VVP} test_edge_detectors.bin

# for the light sequencer
light_sequencer.bit: light_sequencer.sv $(SRCS)
	@echo "########################################"
	@echo "#### Building FPGA bitstream        ####"
	@echo "########################################"
	${VIVADO} build_led.tcl

program_fpga_vivado_led: light_sequencer.bit
	@echo "########################################"
	@echo "#### Programming FPGA (Vivado)      ####"
	@echo "########################################"
	${VIVADO} program_led.tcl

program_fpga_digilent_led: light_sequencer.bit
	@echo "########################################"
	@echo "#### Programming FPGA (Digilent)    ####"
	@echo "########################################"
	djtgcfg enum
	djtgcfg prog -d CmodA7 -i 0 -f light_sequencer.bit

# for main etch-a-sketch script
main.bit: main.sv $(SRCS)
	@echo "########################################"
	@echo "#### Building FPGA bitstream        ####"
	@echo "########################################"
	${VIVADO} build.tcl

program_fpga_vivado: main.bit
	@echo "########################################"
	@echo "#### Programming FPGA (Vivado)      ####"
	@echo "########################################"
	${VIVADO} program.tcl

program_fpga_digilent: main.bit
	@echo "########################################"
	@echo "#### Programming FPGA (Digilent)    ####"
	@echo "########################################"
	djtgcfg enum
	djtgcfg prog -d CmodA7 -i 0 -f main.bit

# Call this to clean up all your generated files
clean:
	rm -f *.bin *.vcd vivado*.log *.jou vivado*.str *.log *.checkpoint *.bit *.html *.xml

# Call this to generate your submission zip file.
submission:
	zip submission.zip Makefile *.sv README.md docs/* *.tcl *.xdc
